server:
  port: 8082
spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://postgres-analytics:5432/expenses_db
    username: Euser
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
logging:
  level:
    org.springframework.security: DEBUG
