version: '3.8'

networks:
  microservices-network:
    driver: bridge

services:

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
#    depends_on:
#      - config-server
    ports:
      - 8761:8761
    networks:
      - microservices-network
    restart: always

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
    ports:
      - 8080:8080
    networks:
      - microservices-network
    restart: always

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - eureka-server
    ports:
      - 8081:8081
    networks:
      - microservices-network
    environment:
          SPRING_DATASOURCE_USERNAME: "Auser"
          SPRING_DATASOURCE_PASSWORD: "123"
    restart: always

  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: Auser
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    networks:
      - microservices-network
    restart: always

  PGAdmin:
    image: dpage/pgadmin4
    container_name: PGAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - 80:80
      - 443:443
    networks:
      - microservices-network
    restart: always