version: '3.8'

networks:
  microservices-network:
    driver: bridge

services:
  web-service:
    build:
      context: ./web-service
    container_name: web-service
    depends_on:
      - eureka-server
      - api-gateway
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    restart: always


  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    #    depends_on:
    #      - config-server
    ports:
      - 8761:8761
    networks:
      - microservices-network
    restart: always

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
    ports:
      - 8089:8089
    networks:
      - microservices-network
    restart: always

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - eureka-server
    ports:
      - 8081:8081
    networks:
      - microservices-network
    environment:
      SPRING_DATASOURCE_USERNAME: "Admin"
      SPRING_DATASOURCE_PASSWORD: "1234"
    restart: always

  expense-service:
    build:
      context: ./expense-service
    container_name: expense-service
    depends_on:
      - eureka-server
    ports:
      - 8082:8082
    networks:
      - microservices-network
    environment:
      SPRING_DATASOURCE_USERNAME: "Admin"
      SPRING_DATASOURCE_PASSWORD: "1234"
    restart: always

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    depends_on:
      - eureka-server
    ports:
      - 8083:8083
    networks:
      - microservices-network
    environment:
      SPRING_DATASOURCE_USERNAME: "Admin"
      SPRING_DATASOURCE_PASSWORD: "1234"
    restart: always

  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: LBank
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    networks:
      - microservices-network
    restart: always

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    depends_on:
      - eureka-server
    ports:
      - "8084:8084"
    networks:
      - microservices-network
    environment:
      SPRING_DATASOURCE_USERNAME: Admin
      SPRING_DATASOURCE_PASSWORD: 1234
    restart: always

  PGAdmin:
    image: dpage/pgadmin4
    container_name: PGAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - 80:80
      - 443:443
    networks:
      - microservices-network
    restart: always

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    networks:
      - microservices-network
    restart: always

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - microservices-network
    restart: always
